# Generated by Django 5.0 on 2023-12-26 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_customuser_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='user_name',
            new_name='username',
        ),
    ]
