# Generated by Django 5.0 on 2023-12-28 05:24

import customers.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', customers.manager.CustomUserManager()),
            ],
        ),
    ]
